---
title: 'final'
author: "Jung Ho Suh"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
  ***S&P INDEX and FINDING OUT ITS ETF'S PROFIT, RELIABILITY***
  
  ***The name(s) of team member(s)***
    Jung Ho Suh
    
  ***The link to the data source***
    SPY Dataset
    https://finance.yahoo.com/quote/SPY/history/
    
    QQQ Dataset
    https://finance.yahoo.com/quote/QQQ/history/
    
    TQQQ Dataset
    https://finance.yahoo.com/quote/TQQQ/history/
    
  ***An overview of the dataset***
  
```{r}
library(readxl)
dailySPY <- read.csv('SPY.csv')
dailyQQQ <- read.csv('QQQ.csv')
dailyTQQQ <- read.csv('TQQQ.csv')

annual_QQQ_2000 <- read_excel('edit_QQQ_2000_Portfolio.xlsx', sheet='Annual Return')
annual_QQQ_2011 <- read_excel('edit_QQQ_2011_Portfolio.xlsx', sheet='Annual Return')
annual_TQQQ_2011 <- read_excel('edit_TQQQ_2011_Portfolio.xlsx', sheet='Annual Return')
annual_SPY_2000 <- read_excel('edit_SPY_2000_Portfolio.xlsx', sheet='Annual Return')

monthly_QQQ_2000 <- read_excel('edit_QQQ_2000_Portfolio.xlsx', sheet='Monthly Return')
monthly_QQQ_2011 <- read_excel('edit_QQQ_2011_Portfolio.xlsx', sheet='Monthly Return')
monthly_TQQQ_2011 <- read_excel('edit_TQQQ_2011_Portfolio.xlsx', sheet='Monthly Return')
monthly_SPY_2000 <- read_excel('edit_SPY_2000_Portfolio.xlsx', sheet='Monthly Return')

crash_QQQ_2000 <- read_excel('edit_QQQ_2000_Portfolio.xlsx', sheet='Historical Crash')
crash_QQQ_2011 <- read_excel('edit_QQQ_2011_Portfolio.xlsx', sheet='Historical Crash')
crash_TQQQ_2011 <- read_excel('edit_TQQQ_2011_Portfolio.xlsx', sheet='Historical Crash')
crash_SPY_2000 <- read_excel('edit_SPY_2000_Portfolio.xlsx', sheet='Historical Crash')

drawdown_QQQ_2000 <- read_excel('edit_QQQ_2000_Portfolio.xlsx', sheet='Drawdown')
drawdown_QQQ_2011 <- read_excel('edit_QQQ_2011_Portfolio.xlsx', sheet='Drawdown')
drawdown_TQQQ_2011 <- read_excel('edit_TQQQ_2011_Portfolio.xlsx', sheet='Drawdown')
drawdown_SPY_2000 <- read_excel('edit_SPY_2000_Portfolio.xlsx', sheet='Drawdown')

str(annual_QQQ_2000)
```
  
  The dataset is comprised of open, high, low, close, Adjusted Close, and Volume.
  
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

joined_QQQ_TQQQ <- annual_QQQ_2011 %>%
  left_join(annual_TQQQ_2011, by = c("Year" = "Year"))

plt1 <- joined_QQQ_TQQQ %>% 
  ggplot(aes(x=Year)) +
    geom_line(aes(y=Balance.x,colour = "QQQ")) + 
    geom_line(aes(y=Balance.y,colour = "TQQQ")) +
    geom_point(aes(y=Balance.x,colour = "QQQ")) +
    geom_point(aes(y=Balance.y,colour = "TQQQ")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    scale_x_continuous(breaks = joined_QQQ_TQQQ$Year, labels = as.character(joined_QQQ_TQQQ$Year)) +
    scale_y_continuous(labels=scales::dollar_format()) +
    labs(title = "QQQ vs TQQQ", y="Balance")

monthly_joined_QQQ_TQQQ <- monthly_QQQ_2011 %>%
  left_join(monthly_TQQQ_2011, by = c("Year" = "Year", "Month" = "Month")) %>%
  mutate(
    Date = as.Date(paste(Year, Month, "01", sep = "-"))
  ) 

plt2 <- monthly_joined_QQQ_TQQQ %>% 
  ggplot(aes(x=Date)) +
    geom_line(aes(y=Balance.x,colour = "QQQ")) + 
    geom_line(aes(y=Balance.y,colour = "TQQQ")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    scale_x_date(date_breaks = "1 year", date_labels =  "%Y") +
    scale_y_continuous(labels=scales::dollar_format()) +
    labs(title = "QQQ vs TQQQ", y="Balance")


show(plt1)
show(plt2)

```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

joined_QQQ_SPY <- annual_QQQ_2000 %>%
  left_join(annual_SPY_2000, by = c("Year" = "Year"))

plt1 <- joined_QQQ_SPY %>% 
  ggplot(aes(x=Year)) +
    geom_line(aes(y=Balance.x,colour = "QQQ")) + 
    geom_line(aes(y=Balance.y,colour = "SPY")) +
    geom_point(aes(y=Balance.x,colour = "QQQ")) +
    geom_point(aes(y=Balance.y,colour = "SPY")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    scale_x_continuous(breaks = joined_QQQ_SPY$Year, labels = as.character(joined_QQQ_SPY$Year)) +
    scale_y_continuous(labels=scales::dollar_format()) +
    labs(title = "QQQ vs SPY", y="Balance")

monthly_joined_QQQ_SPY <- monthly_QQQ_2000 %>%
  left_join(monthly_SPY_2000, by = c("Year" = "Year", "Month" = "Month")) %>%
  mutate(
    Date = as.Date(paste(Year, Month, "01", sep = "-"))
  ) 

plt2 <- monthly_joined_QQQ_SPY %>% 
  ggplot(aes(x=Date)) +
    geom_line(aes(y=Balance.x,colour = "QQQ")) + 
    geom_line(aes(y=Balance.y,colour = "SPY")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    scale_x_date(date_breaks = "1 year", date_labels =  "%Y") +
    scale_y_continuous(labels=scales::dollar_format()) +
    labs(title = "QQQ vs SPY", y="Balance")

show(plt1)
show(plt2)



```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

plt1 <- monthly_joined_QQQ_SPY %>%
  filter(Date > as.Date('2000-01-01') & Date < as.Date('2002-12-01')) %>%
  ggplot(aes(x=Date)) +
    geom_line(aes(y=Balance.x,colour = "QQQ")) + 
    geom_line(aes(y=Balance.y,colour = "SPY")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    scale_x_date(date_breaks = "1 month", date_labels =  "%m-%Y") +
    scale_y_continuous(labels=scales::dollar_format()) +
    labs(title = "Dotcom Crash QQQ vs SPY", y="Balance")

plt2 <- monthly_joined_QQQ_SPY %>%
  filter(Date > as.Date('2007-06-01') & Date < as.Date('2009-08-01')) %>%
  ggplot(aes(x=Date)) +
    geom_line(aes(y=Balance.x,colour = "QQQ")) + 
    geom_line(aes(y=Balance.y,colour = "SPY")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    scale_x_date(date_breaks = "1 month", date_labels =  "%m-%Y") +
    scale_y_continuous(labels=scales::dollar_format()) +
    labs(title = "Subprime Crisis QQQ vs SPY", y="Balance")

plt3 <- monthly_joined_QQQ_SPY %>%
  filter(Date > as.Date('2019-09-01') & Date < as.Date('2020-08-01')) %>%
  ggplot(aes(x=Date)) +
    geom_line(aes(y=Balance.x,colour = "QQQ")) + 
    geom_line(aes(y=Balance.y,colour = "SPY")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    scale_x_date(date_breaks = "1 month", date_labels =  "%m-%Y") +
    scale_y_continuous(labels=scales::dollar_format()) +
    labs(title = "Covid-19 QQQ vs SPY", y="Balance")


show(plt1)
show(plt2)
show(plt3)
```


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

edit_crash_QQQ_2000 <- crash_QQQ_2000 %>% 
  select(`Stress Period`, `Portfolio 1`) %>%
  mutate(
    Ticker = "QQQ",
    Value = `Portfolio 1`*100
  )

edit_crash_SPY_2000 <- crash_SPY_2000 %>% 
  select(`Stress Period`, `Portfolio 1`) %>%
  mutate(
    Ticker = "SPY",
    Value = `Portfolio 1`*100
  )

#joined_crash_QQQ_SPY <- edit_crash_QQQ_2000 %>%
#  left_join(edit_crash_SPY_2000, by = c("Stress Period" = "Stress Period"))

added_crash_QQQ_SPY <- rbind(edit_crash_QQQ_2000, edit_crash_SPY_2000)


plt1 <- added_crash_QQQ_SPY %>% 
    group_by(`Stress Period`) %>%
    ggplot(aes(x=`Stress Period`, y = Value, fill = Ticker)) + 
    geom_bar(position = "dodge", stat = "identity")
show(plt1)

```